// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgwuDIgu5qlSHXAZrVLCBrnifoSe0Y7_I',
    appId: '1:489182032783:web:6e7ce0f3d4fe39f6fcd1fa',
    messagingSenderId: '489182032783',
    projectId: 'litterlens-8b63e',
    authDomain: 'litterlens-8b63e.firebaseapp.com',
    storageBucket: 'litterlens-8b63e.firebasestorage.app',
    measurementId: 'G-XLKBFQM9HF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ya5sWAsDEQyFRYy34c44ukgJbQG1tg4',
    appId: '1:489182032783:android:17c79920179ba78bfcd1fa',
    messagingSenderId: '489182032783',
    projectId: 'litterlens-8b63e',
    storageBucket: 'litterlens-8b63e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD22ElckyS5UhDM850IjZmVsRuerYjpFq4',
    appId: '1:489182032783:ios:a1862cb181436a11fcd1fa',
    messagingSenderId: '489182032783',
    projectId: 'litterlens-8b63e',
    storageBucket: 'litterlens-8b63e.firebasestorage.app',
    iosBundleId: 'com.example.litterLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD22ElckyS5UhDM850IjZmVsRuerYjpFq4',
    appId: '1:489182032783:ios:a1862cb181436a11fcd1fa',
    messagingSenderId: '489182032783',
    projectId: 'litterlens-8b63e',
    storageBucket: 'litterlens-8b63e.firebasestorage.app',
    iosBundleId: 'com.example.litterLens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgwuDIgu5qlSHXAZrVLCBrnifoSe0Y7_I',
    appId: '1:489182032783:web:ba07d15f1d90c2c1fcd1fa',
    messagingSenderId: '489182032783',
    projectId: 'litterlens-8b63e',
    authDomain: 'litterlens-8b63e.firebaseapp.com',
    storageBucket: 'litterlens-8b63e.firebasestorage.app',
    measurementId: 'G-GHHY1KBZ2Z',
  );
}
